version: '3.9'

services:
  app:
    build:
      context: ./app
    container_name: s3-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - s3-network

  ui:
    build:
      context: ./ui
    container_name: s3-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./ui:/app
    networks:
      - s3-network

  db:
    image: postgres:15
    container_name: s3-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - s3-network

volumes:
  postgres_data:
    driver: local

networks:
  s3-network:
    driver: bridge
